export const GET_POST_REQUEST='GET_POST_REQUEST';
export const GET_POST_SUCCESS='GET_POST_SUCCESS';
export const GET_POST_FAILURE='GET_POST_FAILURE';

export const GET_ALL_POSTS_REQUEST='GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS='GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILURE='GET_ALL_POSTS_FAILURE';

